language: node_js
git:
  submodules: false
cache:
  yarn: true
  npm: true
services:
  - mongodb
before_install:
  - npm i -g npm@6.1.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn global add codecov
after_success:
  - codecov